[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
extend-select = [
    "S",    # flake8-bandit
    "E",    # pycodestyle
    "F",    # pyflakes
    "W",    # pycodestyle warnings
    "I",    # isort
    #"C90",  # McCabe complexity, add later
]
ignore = ["E203", "E731", "E501", "E741"]  # remove "E501", "E741" later

[tool.ruff.format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true

[tool.ruff.lint.extend-per-file-ignores]
"improver_tests/*" = ["S101"]
"doc/source/examples/*" = ["E402"]

[tool.coverage.run]
omit = [
    "improver/cli/*",
]