# Use this file to create a conda environment using:
# conda create -n <name> --file environment.yml
# This is for use with Read the Docs.

name: improver
channels:
  - conda-forge
dependencies:
  - python=3
  - iris>=3.12.2
  - python-stratify
  - clize
  - pip
  - pip:
    - cf_units
    - ipykernel
    - nbsphinx   
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx-book-theme    
    - sphinx-gallery
