# Use this file to create a conda environment using:
# conda create -n <name> --file environment.yml
# This is for use with Read the Docs.

name: improver
channels:
  - conda-forge
dependencies:
  - python=3.7
  - iris=3.0
  - cf_units
  - python-stratify
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - pip
  - pip:
    - clize
