# Use this file to create a conda environment using:
# conda create -n <name> --file environment.yml
# This is for use with Read the Docs.

name: improver
channels:
  - conda-forge
dependencies:
  - python=3.13  # https://github.com/SciTools/iris/issues/6762
  - iris>=3.12.2
  - python-stratify
  - clize
  - ipykernel
  - geopandas
  - pandas
  - cf-units
  - joblib
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-book-theme    
  - sphinx-gallery
