# Use this file to create a conda environment using:
# conda env create --file envs/environment_py37_iris30.yml

name: improver_py37_iris30
channels:
  - conda-forge
dependencies:
  - python=3.7
  # Required
  - cartopy=0.19
  - cftime<1.5
  - cf-units=2.1.5
  - clize
  - dask
  - iris=3.0
  - netCDF4
  - numpy<1.21
  - pandas
  - python-dateutil
  - python-stratify
  - pytz=2020.5
  - scipy=1.6
  - sigtools
  - sphinx
  # Optional
  - fastparquet
  - numba
  - pysteps=1.4.1
  - statsmodels
  - timezonefinder=4.1.0
  # Development
  - astroid
  - bandit
  - black=19.10b0
  - codacy-coverage
  - filelock
  - flake8
  - isort=5.*
  - mock
  - mypy
  - pytest
  - pytest-cov
  - pytest-xdist
  - safety
  - sphinx-autodoc-typehints
