# This environment is a representative example for usage of IMPROVER
# It does not include dependencies for the following IMPROVER CLIs:
# estimate-emos-coefficients, nowcast-accumulate, nowcast-extrapolate, 
# nowcast-optical-flow-from-winds, and stochastic-noise.
# See doc/source/Dependencies.rst for more information.
name: improver_b
channels:
  - conda-forge
dependencies:
  - python=3.12
  # Required
  - cartopy
  - clize
  - iris=3.12
  - numpy=2.2
  - pandas<3  # https://github.com/SciTools/iris/issues/6761
  - pytz
  - scipy=1.15
  - sphinx<9.0.0  # https://github.com/tox-dev/sphinx-autodoc-typehints/issues/586
  # Optional
  - geopandas
  - lightgbm>=4.0.0
  - numba
  - python-stratify
  - treelite>=4.0.0
  - tl2cgen>=1.0.0
  # Development
  - astroid
  - filelock
  - mock
  - mypy
  - pytest
  - pytest-cov
  - pytest-xdist
  - sphinx-autodoc-typehints
  - sphinx-book-theme  
  - sphinx-gallery
  - threadpoolctl
  - pip
  - pip:
    - git+https://github.com/metoppv/improver_example_data.git@${BRANCH_NAME}
