# This environment is a representative example for usage of IMPROVER
name: improver_a
channels:
  - conda-forge
dependencies:
  - python=3.12
  # Required
  - cartopy
  - clize
  - iris=3.12
  - numpy=2.2
  - pandas
  - pytz
  - scipy=1.15
  - sphinx
  # Optional
  - fastparquet
  - statsmodels
  - geopandas
  - numba
  - pygam<0.11
  - pysteps
  - python-stratify
  # Development
  - astroid
  - codacy-coverage
  - filelock
  - mock
  - mypy
  - pytest
  - pytest-cov
  - pytest-xdist
  - sphinx-autodoc-typehints
  - sphinx-book-theme  
  - sphinx-gallery
  - threadpoolctl
  - pip
  - pip:
    - git+https://github.com/metoppv/improver_example_data.git@${BRANCH_NAME} 