name: Master Update

on:
  push:
    branches:
      - master  # Triggers when commits are pushed or merged into master
# on: [pull_request]  # uncomment for testing purposes

jobs:
  Test-Coverage:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Environment creation
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: envs/latest.yml
        init-shell: bash
        cache-environment: true

    - name: Environment info
      run: |
        micromamba info
        micromamba list
      shell: bash -el {0}

    - name: pytest
      run: |
          pytest --cov=improver --cov-report=term --cov-report=html | tee coverage_output.txt; test ${PIPESTATUS[0]} -eq 0
      shell: micromamba-shell {0}

    - name: Commit and push documentation changes
      run: |
        git config user.name github-actions[bot]
        git config user.email "github-actions[bot]@users.noreply.github.com"

        mkdir -p /tmp/coverage
        cp coverage_output.txt /tmp/coverage/
        cp -r htmlcov /tmp/coverage/.

        git fetch origin coverage-reference || true
        git checkout -B coverage-reference

        # Remove old coverage files and copy new ones in
        rm -rf coverage_output.txt htmlcov/
        cp /tmp/coverage/coverage_output.txt .
        cp -r /tmp/coverage/htmlcov ./htmlcov

        # Commit and push if there are changes
        git add coverage_output.txt htmlcov/
        git commit --amend --no-edit || echo "No changes to commit"
        git push origin -f coverage-reference
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}