name: Tests

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      id: cache
      with:
        path: /usr/share/miniconda/envs/improver
        key: ${{ runner.os }}-conda-improver-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.OS }}-conda-improver-
    - name: Build conda
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda env update -q --file environment.yml --name improver
        conda list --export
    - name: Source conda
      run:  echo "::add-path::/usr/share/miniconda/envs/improver/bin"
    - name: Pycodestyle (PEP8 conventions)
      run:  pycodestyle -v  improver improver_tests
    - name: Sphinx-build (Doc test)
      run: make -C doc html
    - name: Pytest (Unit tests)
      run: pytest -m "not acc"
    - name: Pylint (More linting goodness)
      run: pylint -j 0 -E --rcfile=etc/pylintrc improver improver_tests
