name: Tests

on: [pull_request, push]
jobs:
  Sphinx-Pytest-Coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [py37_iris30, py38_iris30]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      env:
        # Increase this value to reset cache
        CACHE_NUMBER: 2
      with:
        path: /usr/share/miniconda/envs/improver_${{ matrix.env }}
        key: ${{ format('{0}-conda-improver-{1}-{2}-{3}', runner.os, env.CACHE_NUMBER, matrix.env, hashFiles(format('envs/environment_{0}.yml', matrix.env))) }}
    - name: conda env update
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda install -c conda-forge mamba
        mamba env update -q --file envs/environment_${{ matrix.env }}.yml --name improver_${{ matrix.env }}
    - name: conda info
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        conda info
        conda list
    - name: sphinx-build
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        make -C doc html SPHINXOPTS="-W --keep-going"
    - name: pytest unit-tests & cov-report
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        pytest --cov=improver --cov-report xml:coverage.xml
    - name: codacy-coverage
      if: env.CODACY_PROJECT_TOKEN
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        python-codacy-coverage -v -r coverage.xml
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    - uses: codecov/codecov-action@v1
  Codestyle-and-flake8:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [py37_iris30]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      env:
        # Increase this value to reset cache
        CACHE_NUMBER: 2
      with:
        path: /usr/share/miniconda/envs/improver_${{ matrix.env }}
        key: ${{ format('{0}-conda-improver-{1}-{2}-{3}', runner.os, env.CACHE_NUMBER, matrix.env, hashFiles(format('envs/environment_{0}.yml', matrix.env))) }}
    - name: conda env update
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda install -c conda-forge mamba
        mamba env update -q --file envs/environment_${{ matrix.env }}.yml --name improver_${{ matrix.env }}
    - name: conda info
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        conda info
        conda list
    - name: isort
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        isort --check-only .
    - name: black
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        black --check .
    - name: flake8
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        flake8 improver improver_tests
  Safety-Bandit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [py37_iris30, py38_iris30]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      env:
        # Increase this value to reset cache
        CACHE_NUMBER: 2
      with:
        path: /usr/share/miniconda/envs/improver_${{ matrix.env }}
        key: ${{ format('{0}-conda-improver-{1}-{2}-{3}', runner.os, env.CACHE_NUMBER, matrix.env, hashFiles(format('envs/environment_{0}.yml', matrix.env))) }}
    - name: conda env update
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda install -c conda-forge mamba
        mamba env update -q --file envs/environment_${{ matrix.env }}.yml --name improver_${{ matrix.env }}
    - name: conda info
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        conda info
        conda list
    - name: safety
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        safety check || true
    - name: bandit
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        bandit -r improver
  Type-checking:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [py37_iris30]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      env:
        # Increase this value to reset cache
        CACHE_NUMBER: 2
      with:
        path: /usr/share/miniconda/envs/improver_${{ matrix.env }}
        key: ${{ format('{0}-conda-improver-{1}-{2}-{3}', runner.os, env.CACHE_NUMBER, matrix.env, hashFiles(format('envs/environment_{0}.yml', matrix.env))) }}
    - name: conda env update
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda install -c conda-forge mamba
        mamba env update -q --file envs/environment_${{ matrix.env }}.yml --name improver_${{ matrix.env }}
    - name: conda info
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        conda info
        conda list
    - name: mypy
      run: |
        source '/usr/share/miniconda/etc/profile.d/conda.sh'
        conda activate improver_${{ matrix.env }}
        mypy improver || true
